version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    rabbitmq:
        image: rabbitmq:3-management-alpine

    kanbersky.cleanarch.basket.api:
        image: ${DOCKER_REGISTRY-}kanberskycleanarchbasketapi
        build:
            context: .
            dockerfile: src/Basket/Kanbersky.CleanArch.Basket.Api/Dockerfile
            
    kanbersky.cleanarch.catalog.api:
        image: ${DOCKER_REGISTRY-}kanberskycleanarchcatalogapi
        build:
            context: .
            dockerfile: src/Catalog/Kanbersky.CleanArch.Catalog.Api/Dockerfile