version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    orderdb:
        image: mcr.microsoft.com/mssql/server

    rabbitmq:
        image: rabbitmq:3-management-alpine

    kanbersky.cleanarch.basket.api:
        image: ${DOCKER_REGISTRY-}kanberskycleanarchbasketapi
        build:
            context: .
            dockerfile: src/Basket/Kanbersky.CleanArch.Basket.Api/Dockerfile
            
    kanbersky.cleanarch.catalog.api:
        image: ${DOCKER_REGISTRY-}kanberskycleanarchcatalogapi
        build:
            context: .
            dockerfile: src/Catalog/Kanbersky.CleanArch.Catalog.Api/Dockerfile

    kanbersky.cleanarch.order.api:
        image: ${DOCKER_REGISTRY-}kanberskycleanarchorderapi
        build:
            context: .
            dockerfile: src/Order/Kanbersky.CleanArch.Order.Api/Dockerfile
  
    kanbersky.cleanarch.apigateway:
        image: ${DOCKER_REGISTRY-}kanberskycleanarchapigateway
        build:
            context: .
            dockerfile: src/ApiGateway/Kanbersky.CleanArch.ApiGateway/Dockerfile